### ISSUE TITLE
Блок welcome screen 

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#10]
- [x] Пометить фрагмент кода, целиком отвечающий за welcome page (чтобы можно было его скопировать и перенести)
- [ ] Изображения ожидаются после 15.03
- [x] Тексты ожидаются после 10.03

**Comment by SirSerje** [comment]
![2](https://cloud.githubusercontent.com/assets/9842485/24271193/f00e30bc-1020-11e7-9991-0fa2cf254c0d.png)
### БЛОК 2
НЕЗАБУТНІ СПОГАДИ
Ваша ідея разом з нами стане реальністю!
Нова, сучасна, стильна фотостудія в Києві за розумною ціною.

![3](https://cloud.githubusercontent.com/assets/9842485/24271195/f037938a-1020-11e7-9c4f-97939a1da80f.png)
### БЛОК 3
СТИЛЬНІ СВІТЛИНИ
Нова, сучасна та доступна фотостудія  не тільки для реалізації Ваших творчих ідей та професійного зростання, а також для індивідуальних та сімейних фотосесій.

![4](https://cloud.githubusercontent.com/assets/9842485/24271194/f0325410-1020-11e7-8196-e99531223bcc.png)
### БЛОК 4
НЕПЕРЕВЕРШЕНІ ВРАЖЕННЯ
Ми дбаємо про наших клієнтів, тому вартість студії дуже лояльна та приємна в поєднанні з професійним студійним обладнанням.

**Comment by romanmtb** [comment]
Тексты поменял, остались только изображения.
