### ISSUE TITLE
 Блок футера 

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#11]
- [x] Пометить комментариями блоков утро – его начало и конец
- [ ] Тексты ожидаются после 25.03 (не критичны для данной задачи)
- [x] отредактировать блок, убрав ненужное (ненужное закрашено красным цветом)
- [x] в блок иконок добавить лого в вк
- [x] ссылки на социальные сети должны при нажатии вести на них (на vk.com / fb.com g+.com соотвественно)
- [x] клик на email адресс должен вызывать [mailto:](http://htmlbook.ru/samhtml/ssylki/ssylka-na-adres-elektronnoy-pochty)
![fixit](https://cloud.githubusercontent.com/assets/9842485/23592246/7fbfda18-0206-11e7-8214-d124b646a431.png), клик по телефону ничего не должен делать

**Comment by romanmtb** [comment]
Всё кроме клика по почте удалось, с кликом траблы, по этому хау ты не удается, стили перегаживаются, надо подумать как сделать

**Comment by SirSerje** [comment]
![26](https://cloud.githubusercontent.com/assets/9842485/24271846/6e3a31c8-1023-11e7-8d89-337148d5b5c1.png)
### БЛОК 26
Є зміни в самому файлі, а також 
І зробити футер сірого кольору ( такі як літери Copyrights © 2014 All Rights Reserved by Canvas Inc. ), а літери зробити білими)

**Comment by romanmtb** [comment]
Новые изменения внесены(кроме телефона, я его нигде не нашел)
![2017-03-24 18-42-41](https://cloud.githubusercontent.com/assets/22170734/24301854/54f8c1e8-10b9-11e7-9581-f29d2af33935.png)

**Comment by romanmtb** [comment]
сделал кликабельную почту, но она теперь по умолчанию зеленая, а при наведении белеет, а должно быть наоборот
