### ISSUE TITLE
Блок календарь

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#12]
- [ ] Дизайн и цветовое оформление перенести из созданного шаблона ( который формате jpg).
- [x] Сам календарь перенести из кода, который был вставлен рамках разработки календаря, необходимо раньше, чем поступит рабочее изображение
- [x] Проверить поддержку на мобильных устройствах, сжав браузер на минимальную ширину (при выполненных предыдущих действиях
- [ ] Изображение для фона ожидается 20.03
- [ ] Вставить тестовое изображение
- [x] В аккаунте google поменять стиль отображения календаря на еженедельник

**Comment by SirSerje** [comment]
Календарь перенес в соответствии с требованиями заказчика
На мобильной версии выглядит терпимо. Хорошо выглядит с 480 пикселей ширины

**Comment by SirSerje** [comment]
Под календарем разместить кнопку **Замовити**  которая ведет на контакты

**Comment by SirSerje** [comment]
Кнопка по центру, ведет к блоку отправки формы

**Comment by romanmtb** [comment]
Кнопку заменил, сделал плавный скролл на контакты.
