### ISSUE TITLE
Блок фотографии

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#13]
- [x] Выделить комментариями блок с фотографиями
- [ ] Разобраться в механизме фильтров по этой задаче
- [ ] Добавить заголовок "Наши работы" и текст под ним немного меньше по размеру "Рыбный текст"
- [ ] Фотографии ожидаются после 15.03
- [ ] Тексты для групп ожидаются после 25.03

**Comment by SirSerje** [comment]
![20](https://cloud.githubusercontent.com/assets/9842485/24271810/3d2eea56-1023-11e7-9b3f-9f14da1abf05.png)
### БЛОК 20
Портфоліо ( Світлини)

![21](https://cloud.githubusercontent.com/assets/9842485/24271816/443d3c30-1023-11e7-83fc-9ff9114d1865.png)
### БЛОК 21 
Видалити

![22](https://cloud.githubusercontent.com/assets/9842485/24271820/4bcbf3d8-1023-11e7-9f62-e3c96678bfc1.png)
### БЛОК 22
Спочатку говорили про фотокалаж ( одні фото більші, інші – менші) – набір різних фото,
А при нажатті на будь-яке фото, то відкривається галерея, де можна подивитись кожну фото окремо
**На утверждении**

**Comment by romanmtb** [comment]
Тут я не совсем понимаю что нужно сделать, этот блок им не нравится и его надо заменить? @SirSerje

**Comment by SirSerje** [comment]
С фотографиями им надо предложить варианты, галерей.
Можешь дать ссылки на все галереи из примера, комментарием в эту задачу?

**Comment by SirSerje** [comment]
Вставляем такую галерею
http://spaceport.sj-photostudio.com/gallery.html 4 Column
![viber image](https://cloud.githubusercontent.com/assets/9842485/24876764/96f0f3fc-1e35-11e7-87b0-aa6b367d11a3.jpg)

**Comment by romanmtb** [comment]
![2017-04-11 00-07-58](https://cloud.githubusercontent.com/assets/22170734/24882784/f2a75514-1e4a-11e7-8254-70b7e4db02fb.png)
Сделал

**Comment by SirSerje** [comment]
Ожидаю пулриквеста
