### ISSUE TITLE
Блок услуги

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#14]
- [x] перенести базовый блок "услуги"
- [x] Вставить в формате png (фон обрезать) картинку оборудования для [фотографии ](http://g04.a.alicdn.com/kf/HTB1k_nKJXXXXXXyXXXXq6xXFXXXH/%D0%A4%D0%BE%D1%82%D0%BE%D0%B0%D0%BF%D0%BF%D0%B0%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%B0-%D1%81%D1%82%D1%83%D0%B4%D0%B8%D0%B8-%D0%BE%D1%81%D0%B2%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D1%8F-%D1%84%D0%BB%D1%8D%D1%88-%D0%BA%D0%B0%D0%BC%D0%B5%D1%80%D0%B0-%D1%81%D1%82%D1%80%D0%BE%D0%B1-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%82-%D1%84%D0%BE%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%B8-%D1%81%D0%B2%D0%B5%D1%82.jpg)
- [x] Выделить комментариями код, отвечающий за данный блок
- [ ] Блок, где используються иконки наполнить иконками из шаблона, в которых есть любые вариации на тему фотографии и соц сетей (частично)
 - [ ] Изображение (фотоколлаж) ожидается после 23.03

**Comment by SirSerje** [comment]
![12](https://cloud.githubusercontent.com/assets/9842485/24271526/267be9b8-1022-11e7-85b7-3312a2a9a4c1.png)
### БЛОК 12
НАШІ ПОСЛУГИ
Ми  раді Вам запропонувати широкий ряд додаткових послуг ( фотостудії ( слово фотостудії додамо, якщо текст буде гарно дивитись)

![13](https://cloud.githubusercontent.com/assets/9842485/24271570/538083a6-1022-11e7-9f90-47d00f13c22a.png)
### БЛОК 13
Замість картинка телефонів, висилаю файл під назвою Сайт техніка. Чи підходить така картинка?
**Картинку подготовят**

![14](https://cloud.githubusercontent.com/assets/9842485/24271583/62843320-1022-11e7-853d-ddcfd981931e.png)
### БЛОК 14
ФОТОГРАФ  
ми співпрацюємо з досвідченими фотографами, які з радістю допоможуть Вам втілити ваші ідеї та отримати неповторні світлини ( від 500грн/год)

![15](https://cloud.githubusercontent.com/assets/9842485/24271592/69858cdc-1022-11e7-82d2-3a6028abd9c2.png)
### БЛОК 15
АСИСТЕНТ ФОТОГРАФА 
Один професіонал це - добре, але коли їх двоє – ще краще.  Фотосесія проходить легко, швидко та позитивно ( від 200 грн/год)

![16](https://cloud.githubusercontent.com/assets/9842485/24271595/6e3888d8-1022-11e7-9433-ca8cdbb3346d.png)
### БЛОК 16
ВІЗАЖИСТ ТА СТИЛІСТ-ПЕРУКАР
Допомога у втіленні будь-якого образу ( від 800 грн)

![17](https://cloud.githubusercontent.com/assets/9842485/24271606/74216bb6-1022-11e7-9788-a46bc982d790.png)
### БЛОК 17
ОБРОБКА ФОТОГРАФІЙ
Корекція, редагування та художня обробка світлин ( від 10 грн/фото)

![18](https://cloud.githubusercontent.com/assets/9842485/24271618/8170ae94-1022-11e7-8172-fae2c5bfbc94.png)
### БЛОК 18
ЗБЕРІГАННЯ ВАШИХ РЕКВІЗИТІВ
Пропонуємо зберігання будь-яких реквізитів.
Параметри фотостудії дозволяють зберігати навіть досить масивні реквізити.  Кожна ситуація розглядається індивідуально Для більш детальної інформації, звертайтесь до адміністрації ( від 100 грн/день)

![19](https://cloud.githubusercontent.com/assets/9842485/24271631/887092e0-1022-11e7-86b7-41ea7fcf1c91.png)
### БЛОК 19
Поки що відстутній. Можливо, ще щось придумаєм. Якщо ні, то тоді те що є, треба розташувати красиво

**Comment by romanmtb** [comment]
Всё что на данный момент можно было сделать сделано.

**Comment by romanmtb** [comment]
![2017-03-31 23-13-00](https://cloud.githubusercontent.com/assets/22170734/24567732/42b98caa-165f-11e7-8d04-9bd32f54bc6f.png)
Иконки вставил самые подходящие.
