### ISSUE TITLE
Блок Залы

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#15]
- [x] Комментариями обозначить блок кода, отвечащий за данный контент
- [ ] Добавить пару иконок (малого размера)
- [x] Создать третью фотографию зала и увеличить ее высоту на 100 пикселей (без потери функционала) и ее менюшка должна не выпадать а быть статично открытой
- [x] Тексты ожидаются 10.03
- [ ] Изображения ожидаются 15.03
- [ ] Залов будет всего пока 2. Для второго вставить изображение Coming Soon
- [ ] Добавить к каждому залу поле цена и жирным 1.5 размера значение цены

**Comment by SirSerje** [comment]
![5](https://cloud.githubusercontent.com/assets/9842485/24271258/33f156b0-1021-11e7-97de-fecc5e02e996.png)

### БЛОК 5
ФОТОЗАЛИ
Запрошуємо вас відвідати наші оригінальні інтер’єри з сучасними цікавими ідеями

![6](https://cloud.githubusercontent.com/assets/9842485/24271307/5ca206cc-1021-11e7-8fa7-9410e77e6d73.png)
### БЛОК 6
Зелена Зала
Media, Icons - видалити
Основний текст:
В даному залі  представлено 6 локацій  в різних стильових рішеннях. Різноманітність локацій дозволяє зробити світлини в різних жанрах. 
Студійний комплект Bowens Gemini 750PRO / 750 PRO Kit

Пн-Пт: 
з 10.00 до 22.00  фотозйомка – 300грн/год,  відеозйомка – 400грн/год
з 22.00 до 10.00  фотозйомка – 350грн/год,  відеозйомка – 450 грн/год
Сб-Нд: 
з 10.00 до 22.00 фотозйомка – 350 грн/год,  відеозйомка – 450 грн/год
З 22.00 до 10.00 фотозйомка – 400грн/год,  відеозйомка – 500грн/год
Кнопки Launch Project – видалити, а замість неї текст
Перед бронюванням фотостудії, просимо ознайомитися з Правилами оренди фотостудії ( Правила оренди мають бути виділені, наприклад, насиченим сірим кольором і має відкриватися вікно з правилами оренди

![7](https://cloud.githubusercontent.com/assets/9842485/24271321/6c836e96-1021-11e7-8567-b640264d0bd7.png)
### БЛОК 7
Біла Зала
Illustrator - видалити
Основний текст: поки що не буде

Пн-Пт: 
з 10.00 до 22.00  фотозйомка,  відеозйомка
з 22.00 до 10.00  фотозйомка,  відеозйомка 
Сб-Нд: 
з 10.00 до 22.00 фотозйомка,  відеозйомка
З 22.00 до 10.00 фотозйомка,  відеозйомка
Кнопки Launch Project – видалити, а замість неї текст
Перед бронюванням фотостудії, просимо ознайомитися з Правилами оренди фотостудії ( Правила оренди мають бути виділені, наприклад, насиченим сірим кольором і має відкриватися вікно з правилами оренди

![8](https://cloud.githubusercontent.com/assets/9842485/24271355/8c3a9d18-1021-11e7-9889-2d9122efe3d4.png)
### БЛОК 8
Поставити красиве фото та написати (**это на уточнении**)
СКОРО… (это пишем)

![9](https://cloud.githubusercontent.com/assets/9842485/24271427/cfb7d57e-1021-11e7-89c9-9a80094b9f0a.png)
### БЛОК 9
Сіра Зала
Medai, Icons - видалити
Основний текст: поки що не буде

Пн-Пт: 
з 10.00 до 22.00  фотозйомка,  відеозйомка
з 22.00 до 10.00  фотозйомка,  відеозйомка 
Сб-Нд: 
з 10.00 до 22.00 фотозйомка,  відеозйомка
З 22.00 до 10.00 фотозйомка,  відеозйомка
Кнопки Launch Project – видалити, а замість неї текст
Перед бронюванням фотостудії, просимо ознайомитися з Правилами оренди фотостудії ( Правила оренди мають бути виділені, наприклад, насиченим сірим кольором і має відкриватися вікно з правилами оренди

Там де фото ( як в блоці 8)
Поставити красиве фото та написати
СКОРО…

**Comment by romanmtb** [comment]
Все тексты добавил, фотку каминг сун "красивую" я думаю стоит добавить потом когда будут фотки залов, что бы она стилистически была хоть похожа как то на них.
