### ISSUE TITLE
Блок контакты

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#16]
- [x] Сверстать на основе самого подходящего макета контактов данную страницу
- [x] Подвязать Google Maps (пароль к аккаунту будет предоставлен на Google Drive), локацией указать Выдубичи
- [x] Отделить блок кода контактов комментариями
- [ ] Тексты ожидаются после 25.03
- [ ] В нижней группе иконок располагаются слева направо: локация, телефон, вк, почта (?)

**Comment by SirSerje** [comment]
![23](https://cloud.githubusercontent.com/assets/9842485/24271863/79d4f400-1023-11e7-9e00-0fd4f05da7ed.png)
Блок 23
КОНТАКТИ ТА СХЕМА ПРОЇЗДУ
Маєте запитання? Зв’яжіться з нами або відправте листа

![24](https://cloud.githubusercontent.com/assets/9842485/24271873/867e25c8-1023-11e7-86de-7aac2301a017.png)
Блок 24
Всі зміни в самому файлі безпосередньо
Також форму відправки повідомлення зменшити на 50% або більше при необхідності, щоб знизу  помістився цей текст
Ми відкриті:
Пн – Вс: з 10:00 до 22:00
Нічна зйомка за попереднім записом
Контакти:
Номер телефону ( ще нема)
Sjphotostudio.manager@gmail.com
Після внесення 50% від вартості оренди студії, ОБОВЯЗКОВО зв’яжіться  з адміністрацією для  підтвердження бронювання.
Як нас знайти:
м. Київ, вул. Будіндустрії, 7,  ст.м. Видубичі, виходите в голову поїзда, проходите через турнікет та повертаєте праворуч ( орієнтир магазин Фуршет). Біля магазину Фуршет сідаєте на автобус № 54 та виходите на зупинці «ДОК» ( виходите на 2-ій зупинці) . 
Фото зліва допоможе зорієнтуватись 
( На карті вказати червоним маршрут як дістатися від м. Видубичі до самої студії

![25](https://cloud.githubusercontent.com/assets/9842485/24271887/93230cbc-1023-11e7-99d0-5befefd153b8.png)
Блок 25
Всі зміни внесені на самому файлі
Замість джімейл + поставити інстаграм та телефон

**Comment by romanmtb** [comment]
с контактами закончил только тут полная неизвестность надо долго разбираться походу 
![2017-03-26 22-55-12](https://cloud.githubusercontent.com/assets/22170734/24334700/73995646-126f-11e7-8a8e-8def3b19e7d2.png)
![-44759043_456243093](https://cloud.githubusercontent.com/assets/22170734/24334699/73965a0e-126f-11e7-88f0-b6f33e801556.jpg)
![-44759043_456243093 -](https://cloud.githubusercontent.com/assets/22170734/24334698/73957ada-126f-11e7-9907-55cb9d5f0805.jpg)

**Comment by romanmtb** [comment]
![2017-03-31 22-54-42 1](https://cloud.githubusercontent.com/assets/22170734/24567116/ad89ae3c-165c-11e7-8316-9c4367a789d7.png)
ссылки вставил
