### ISSUE TITLE
Создать рабочую страницу

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#21]
Создать новую страницу с названием index-main.html
В ней должно быть: блок навигации, блок welcome page, пустое пространство, блок футера. Можно оставить для этой задаче в базовом виде, тоесть как в шаблоне.

**Comment by romanmtb** [comment]
Создал рабочую страницу.

**Comment by SirSerje** [comment]
5cd25cdf259009097a28578023837cab0531d016
commit merged into master
