### ISSUE TITLE
Установить WinLess

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#3]
Как сознательные люди, работаем не напряму с css, а на перспективу будем использовать less файлы, поэтому необходимо запастись WinLess компилятором.

_Задача будет закрыта, когда все участники разработки выполнят данное действие на локальном ПК и отпишут в эту задачу._

**Comment by romanmtb** [comment]
Я установил, что и зачем это я выкупаю, но дела вообще не имел, поэтому надо будет еще уроки посмотреть.

**Comment by SirSerje** [comment]
Less менее перспективный нежели sass
