### ISSUE TITLE
Меню навигации в моб версии

### ISSUE THREAD

**Issue by romanmtb** [SirSerje/sj_studio#33]
![102334180_456239316](https://cloud.githubusercontent.com/assets/22170734/23868246/67eff5cc-0827-11e7-8143-0bbd63c11a0e.jpg)
![102334180_456239317](https://cloud.githubusercontent.com/assets/22170734/23868249/6b77f064-0827-11e7-9ea8-68e625820b8d.jpg)

Добавить меню вверху страницы как в one-page.html

**Comment by SirSerje** [comment]
Это "улучшение" которое закладывается при верстке специально под разные версии девайсов. На сильно маленьких девайсах 4" это меню может быть не удобным. Предлагаю оставить до согласования.
Если есть желание, можно запилить реализацию в отдельной ветке

**Comment by SirSerje** [comment]
В мобильной версии все в порядке с переводами?
