### ISSUE TITLE
Подготовить материалы

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#38]
В данную задачу прикрепить 2 комментариями на все возможные 

- [ ] реализации фото галереи 
- [ ] ссылки на картинки (кроме фото галереи) которые используются в проекте
- [x] иконки

**Comment by romanmtb** [comment]
images\logo-dark.png
images\logo-dark@2x.png                   retina
images\slider/swiper\1.jpg
images\slider/swiper\2.jpg
images\slider/swiper\3.jpg
images\portfolio\1/1.jpg
images\portfolio\full\1.jpg
images\portfolio\1/2.jpg
images\portfolio\full\2.jpg
images\services\photo-equip.png

**Comment by romanmtb** [comment]
sj_studio\gallery.html
Тут аж 5 вариантов реализации галереи, а файл с галереями всего один у нас.

**Comment by SirSerje** [comment]
social-icons.html
styled-icons.html
