### ISSUE TITLE
Модальное окно

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#39]
Создать модальное окно к описанию зала

**Comment by SirSerje** [comment]
9ab6f09eaf16f7e1ab9a36fd8e8ed8269d5f6153

**Comment by SirSerje** [comment]
Необходимо актуализировать шапку и добавить кнопку "Погоджуюсь"

**Comment by romanmtb** [comment]
Добавил заголовок, кнопку "Погоджуюсь" и параметр который запрещает закрывать модальное окно при нажатии за его пределами.
