### ISSUE TITLE
Выбрать елементы для реализации блоков сайта

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#4]
Необходимо найти максимально подобные примеры реализации в шаблоне сайта тех блоков, которые должны быть помещены на сайт

В вики сайта есть : https://github.com/SirSerje/sj_studio/wiki/Main-Elements
Можно добавить в этот файл примеры, или создать новый в wiki. 
Можно дать просто описание без скрина или так, чтобы было понятно, где я могу найти этот или другой элемент.

**Comment by romanmtb** [comment]
Сделал
