### ISSUE TITLE
Блок верхней навигации

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#9]
- [x] Убрать блок покупки справа
- [x] добавить для начала всех блоков якорные точки и завязать кнопки на эти якорные точки. Переход не мгновенный а со скроллом. В шаблоне есть пример
- [ ] Отделить блок кода комментариями
- [x] Выключить выпадающие меню - у нас их не будет (если они есть в примере)
- [ ] убрать все кнопки, добавить номер телефона, чтобы он был размера в 1.5 раза больше текущего текста в шапке (цвет не менять). Внимание (**!**) стили в найти в style.css, если его элементов нельзя реализовать, обратиться к @SirSerje -- **не понимаю эту задачу, куда телефон конкретно нужно запилить и какие и какие кнопки убрать?** @SirSerje 
- [ ] логотип ожидается после 10.03

**Comment by SirSerje** [comment]
![1](https://cloud.githubusercontent.com/assets/9842485/24271148/c349bc72-1020-11e7-9f6e-b8bff28ec864.png)
### БЛОК 1
ГОЛОВНА  ЗАЛИ  КАЛЕНДАР ПОСЛУГИ ПОРТФОЛІО КОНТАКТИ

**Comment by romanmtb** [comment]
Названия поменял
